<a href="https://colab.research.google.com/github/vedant3110/PHY_312-Numerical_Methods_IISERB-/blob/main/Gauss_elimination.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install matplotlib numpy scipy

In [2]:
import numpy as np
import scipy as sc
import matplotlib.pyplot as plt
import math as ma

In [30]:
a = np.array([[7,3,-1,2],[3,8,1,-4],[-1,1,4,-1],[2,-4,-1,6]], dtype=float)
b = np.array([80.0, 30.0, 80.0, 20.0], dtype=float)

In [31]:
n=4
for i in range(0,n):
  for j in range(i+1,n):
    factor=a[j,i]/a[i,i]
    for k in range(i+1,n):
      a[j,k]=a[j,k]-factor*a[i,k]
    b[j]=b[j]-factor*b[i]
print(a,b)

[[ 7.          3.         -1.          2.        ]
 [ 3.          6.71428571  1.42857143 -4.85714286]
 [-1.          1.42857143  3.55319149  0.31914894]
 [ 2.         -4.85714286  0.31914894  1.88622754]] [ 80.          -4.28571429  92.34042553 -14.25149701]


In [32]:
x=np.zeros(n)
x[n-1]=b[n-1]/a[n-1,n-1]
for i in range(n-2,-1,-1):
  temp=0
  for j in range(i+1,n):
    temp+=a[i,j]*x[j]
  x[i]=(b[i]-temp)/a[i,i]
print(x)

[ 22.44444444 -11.77777778  26.66666667  -7.55555556]
